server:
  port: 8083
spring:
  application:
    name: spring-rest-security
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/cybertek
    username: postgres
    password: 2754
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: never
      data-locations: classpath:data.sql
security:
  jwt:
    secret-key: cybertek
springdoc:
  swagger-ui:
    path: /swagger-ui.html





